language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main
  travis env set GITHUB_TOKEN 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
